# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------


# Create imported target 
add_library(@TARGET_LIB@ SHARED IMPORTED)
set(@TARGET_LIB@_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../../include")

if(UNIX)
	file(GLOB libs "${CMAKE_CURRENT_LIST_DIR}/../../@PROJ_NAME@/*.so")
else()
	file(GLOB libs "${CMAKE_CURRENT_LIST_DIR}/../../@PROJ_NAME@/*${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()

foreach(entry ${libs})
	string(FIND ${entry} "-gd." pos REVERSE)
	message(STATUS "entry: " ${entry} ", pos: " ${pos})
	if((CMAKE_BUILD_TYPE MATCHES Debug))
		if ((pos GREATER_EQUAL 0))
			list(APPEND "@TARGET_LIB@_LIBRARIES" ${entry})
		endif()
	elseif((pos LESS 0))
		list(APPEND "@TARGET_LIB@_LIBRARIES" ${entry})
	endif()
endforeach()
message(STATUS "@TARGET_LIB@ LIBRARIES: " ${@TARGET_LIB@_LIBRARIES})

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
